//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev3.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int ID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string E_Posta { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string PostaKodu { get; set; }
        public string Tarih { get; set; }
        public int UrunID { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
