//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int ID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Mesaji { get; set; }
        public string Konu { get; set; }
        public string E_Posta { get; set; }
    }
}
